version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
      python: 3.11
    commands:
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      - pip install aws-sam-cli
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - sam package --template-file samTemplate1.yml --s3-bucket $CODEBUILD_RESOLVED_SOURCE_S3_BUCKET --output-template-file packaged-template.yml

artifacts:
  files:
    - packaged-template.yml