AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to forward SQS messages to SNS

Resources:
  SqsToSnsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/sqs-sns-lambda-1.0.0.jar
      Handler: com.example.lambda.SqsToSnsLambda::handleRequest
      Runtime: java17
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaSQSQueueExecutionRole
        - AmazonSNSFullAccess
        - AmazonSQSFullAccess
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:422032868698:module8-UploadsNotificationQueue