AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 and RDS comparison Lambda

Resources:
  S3AndRDSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/sqs-sns-lambda-1.0.0.jar
      Handler: com.example.lambda.S3AndRDSLambda::handleRequest
      Runtime: java17
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          DB_URL: "jdbc:mysql://module10-db.c0z0ykq2yogz.us-east-1.rds.amazonaws.com:3306/module10db"
          DB_USER: "module10user"
          DB_PASSWORD: "module10password"
          DB_TABLE: "image"
          BUCKET_NAME: "ec2-task4-1"
      Policies:
        - AmazonS3ReadOnlyAccess
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadWrite
        - AmazonRDSFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /compare
            Method: post